// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Hamza Ghandouri <hamza.ghandouri@gmail.com> - https://miqraa.org

// Surah display names aligned with frontend/src/data/quran/surahs.json.

const SURAH_NAMES_AR: [&str; 115] = ["",
    "الفَاتِحة",
    "البَقَرَة",
    "آل عِمران",
    "النِّسَاء",
    "المَائدة",
    "الأنعَام",
    "الأعرَاف",
    "الأنفَال",
    "التوبَة",
    "يُونس",
    "هُود",
    "يُوسُف",
    "الرَّعد",
    "إبراهِيم",
    "الحِجر",
    "النَّحل",
    "الإسرَاء",
    "الكَهف",
    "مَريَم",
    "طه",
    "الأنبيَاء",
    "الحج",
    "المؤمنُون",
    "النور",
    "الفُرقَان",
    "الشعراء",
    "النَّمل",
    "القَصَص",
    "العَنكبُوت",
    "الرُّوم",
    "لُقمَان",
    "السَّجدة",
    "الأحزَاب",
    "سَبإ",
    "فَاطِر",
    "يسٓ",
    "الصَّافَات",
    "صٓ",
    "الزُّمَر",
    "غَافِر",
    "فُصِّلَت",
    "الشُّوري",
    "الزُّخرُف",
    "الدُّخان",
    "الجاثِية",
    "الأحقَاف",
    "مُحمد",
    "الفَتح",
    "الحُجُرَات",
    "قٓ",
    "الذَّاريَات",
    "الطُّور",
    "النَّجم",
    "القَمَر",
    "الرَّحمٰن",
    "الوَاقِعة",
    "الحدِيد",
    "المُجَادلة",
    "الحَشر",
    "المُمتَحنَة",
    "الصَّف",
    "الجُمعَة",
    "المُنَافِقُونَ",
    "التغَابُن",
    "الطَّلَاق",
    "التَّحرِيم",
    "المُلك",
    "القَلَم",
    "الحَاقة",
    "المَعَارج",
    "نُوح",
    "الجِن",
    "المُزمل",
    "المُدثر",
    "القِيَامة",
    "الإنسَان",
    "المُرسَلات",
    "النَّبَإ",
    "النَّازعَات",
    "عَبَسَ",
    "التَّكوير",
    "الانفِطَار",
    "المُطَففين",
    "الانشِقَاق",
    "البُرُوج",
    "الطَّارق",
    "الأعلى",
    "الغَاشِية",
    "الفَجر",
    "البَلَد",
    "الشَّمس",
    "اللَّيل",
    "الضُّحى",
    "الشَّرح",
    "التِّين",
    "العَلَق",
    "القَدر",
    "البَينَة",
    "الزَّلزَلة",
    "العَاديَات",
    "القَارعَة",
    "التَّكاثُر",
    "العَصر",
    "الهُمَزة",
    "الفِيل",
    "قُرَيش",
    "المَاعُون",
    "الكَوثر",
    "الكافِرون",
    "النَّصر",
    "المَسَد",
    "الإخلَاص",
    "الفَلَق",
    "النَّاس",
];

const SURAH_NAMES_EN: [&str; 115] = ["",
    "Al-Faatiha",
    "Al-Baqara",
    "Aal-i-Imraan",
    "An-Nisaa",
    "Al-Maaida",
    "Al-An'aam",
    "Al-A'raaf",
    "Al-Anfaal",
    "At-Tawba",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Israa",
    "Al-Kahf",
    "Maryam",
    "Taa-Haa",
    "Al-Anbiyaa",
    "Al-Hajj",
    "Al-Muminoon",
    "An-Noor",
    "Al-Furqaan",
    "Ash-Shu'araa",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankaboot",
    "Ar-Room",
    "Luqman",
    "As-Sajda",
    "Al-Ahzaab",
    "Saba",
    "Faatir",
    "Yaseen",
    "As-Saaffaat",
    "Saad",
    "Az-Zumar",
    "Al-Ghaafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhaan",
    "Al-Jaathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujuraat",
    "Qaaf",
    "Adh-Dhaariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahmaan",
    "Al-Waaqia",
    "Al-Hadid",
    "Al-Mujaadila",
    "Al-Hashr",
    "Al-Mumtahana",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munaafiqoon",
    "At-Taghaabun",
    "At-Talaaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haaqqa",
    "Al-Ma'aarij",
    "Nooh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddaththir",
    "Al-Qiyaama",
    "Al-Insaan",
    "Al-Mursalaat",
    "An-Naba",
    "An-Naazi'aat",
    "Abasa",
    "At-Takwir",
    "Al-Infitaar",
    "Al-Mutaffifin",
    "Al-Inshiqaaq",
    "Al-Burooj",
    "At-Taariq",
    "Al-A'laa",
    "Al-Ghaashiya",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Dhuhaa",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzala",
    "Al-Aadiyaat",
    "Al-Qaari'a",
    "At-Takaathur",
    "Al-Asr",
    "Al-Humaza",
    "Al-Fil",
    "Quraish",
    "Al-Maa'un",
    "Al-Kawthar",
    "Al-Kaafiroon",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlaas",
    "Al-Falaq",
    "An-Naas",
];

const SURAH_NAMES_FR: [&str; 115] = ["",
    "Al Fâtiha",
    "Al Baqarah",
    "Al 'Imran",
    "An Nisâ'",
    "Al Mâ'idah",
    "Al An'am",
    "Al A'raf",
    "Al Anfâl",
    "At Tawbah",
    "Yûnus",
    "Hûd",
    "Yûsuf",
    "Ar Ra'd",
    "Ibrâhîm",
    "Al Hijr",
    "An Nahl",
    "Al Isrâ'",
    "Al Kahf",
    "Maryam",
    "Tâ Hâ",
    "Al Anbiyâ'",
    "Al Hajj",
    "Al Mu'minûn",
    "An Nûr",
    "Al Furqân",
    "Ash Shu'arâ'",
    "An Naml",
    "Al Qasas",
    "Al 'Ankabût",
    "Ar Rûm",
    "Luqmân",
    "As Sajdah",
    "Al Ahzâb",
    "Saba'",
    "Fâtir",
    "Yâ Sîn",
    "As Sâffât",
    "Sâd",
    "Az Zumar",
    "Ghâfir",
    "Fussilat",
    "Ash Shûrâ",
    "Az Zukhruf",
    "Ad Dukhân",
    "Al Jâthiyah",
    "Al Ahqâf",
    "Muhammad",
    "Al Fath",
    "Al Hujurât",
    "Qâf",
    "Adh Dhâriyât",
    "At Tûr",
    "An Najm",
    "Al Qamar",
    "Ar Rahmân",
    "Al Wâqi'ah",
    "Al Hadîd",
    "Al Mujâdalah",
    "Al Hashr",
    "Al Mumtahanah",
    "As Saff",
    "Al Jumu'ah",
    "Al Munâfiqûn",
    "At Taghâbun",
    "At Talâq",
    "At Tahrîm",
    "Al Mulk",
    "Al Qalam",
    "Al Hâqqah",
    "Al Ma'ârij",
    "Nûh",
    "Al Jinn",
    "Al Muzzammil",
    "Al Muddaththir",
    "Al Qiyâmah",
    "Al Insân",
    "Al Mursalât",
    "An Naba'",
    "An Nâzi'ât",
    "'Abasa",
    "At Takwîr",
    "Al Infitâr",
    "Al Mutaffifîn",
    "Al Inshiqâq",
    "Al Burûj",
    "At Târiq",
    "Al A'lâ",
    "Al Ghâshiyah",
    "Al Fajr",
    "Al Balad",
    "Ash Shams",
    "Al Layl",
    "Ad Duhâ",
    "Ash Sharh",
    "At Tîn",
    "Al 'Alaq",
    "Al Qadr",
    "Al Bayyinah",
    "Az Zalzalah",
    "Al 'Âdiyât",
    "Al Qâri'ah",
    "At Takâthur",
    "Al 'Asr",
    "Al Humazah",
    "Al Fîl",
    "Quraysh",
    "Al Mâ'ûn",
    "Al Kawthar",
    "Al Kâfirûn",
    "An Nasr",
    "Al Masad",
    "Al Ikhlâs",
    "Al Falaq",
    "An Nâs",
];

pub fn surah_name(surah: i32, locale: &str) -> &'static str {
    let idx = surah.clamp(0, 114) as usize;
    match locale {
        "ar" => SURAH_NAMES_AR.get(idx).copied().unwrap_or(""),
        "fr" => SURAH_NAMES_FR.get(idx).copied().unwrap_or(""),
        _ => SURAH_NAMES_EN.get(idx).copied().unwrap_or(""),
    }
}
